all: 
	python3 runtest.py

versions/mati/:
	- mkdir versions/mati
	git show b6db27f8d5cc6e363dd2e9f3c95b63b52387b9e6:src/__init__.py > versions/mati/__init__.py
	git show b6db27f8d5cc6e363dd2e9f3c95b63b52387b9e6:src/mathematics.py > versions/mati/mathematics.py

